import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react';
import BaseInput from '@/components/BaseInput';
import Button from '@/components/Button';

const inter = Inter({ subsets: ['latin'] })

// function List(props) {
//   const list = props.list;
//   return (
//     <a href="https://nextjs.org/docs" className={styles.card}>
//         <h3>{list.title} &rarr;</h3>
//         <ul>
//         {list.items && list.items.map((item,index) => (
//             <li key={index}><p>{item}</p></li>
//         ))}
//         </ul>
//     </a>
//   );
// }

export default function Home() {
  const [list, setList] = useState({title: '', items: []});
  // const [lists, setLists] = useState([]);
  const [shareLink, setShareLink] = useState('');

//   useEffect(() => {
//     fetch(`${process.env.NEXT_PUBLIC_API_URL}/lists`)
//        .then((response) => response.json())
//        .then((data) => {
//           setLists(...lists, data.data);
//        });
//  }, []);

 const listHandler = (e)=>{
  setList({...list, title: e.target.value})
}

const createList = async () => {
  await fetch(`${process.env.NEXT_PUBLIC_API_URL}/lists`, {
  method: 'POST',
  body: JSON.stringify({
     title: list.title,
  }),
  headers: {
     'Content-type': 'application/json; charset=UTF-8',
  },
  })
  .then((response) => response.json())
  .then((data) => {
    const newList = {title: data.data.title, uuid: data.data.uuid};
    setShareLink(`${process.env.NEXT_PUBLIC_URL}/lists/${newList.uuid}`);
    // setLists([...lists, newList]);
    setList({title: '', items: []});
  })
  .catch((err) => {
     console.log(err.message);
  });
};

const copy = async () => {
  await navigator.clipboard.writeText(shareLink);
  alert('Text copied');
}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className={styles.description}>
          <p>zuro</p>
        </div> */}

        <div>
          <div className="flex flex-col z-10">
            <h1 className="text-3xl font-bold mb-2">
              Add a title
            </h1>

            <div className='flex space-x-3 pb-8'>
              <BaseInput value={list.title} required onChange={listHandler} />

              <Button pill disabled={list.title == ''} onClick={createList}>
                Create list
              </Button>
            </div>            


            { shareLink != '' && 
              <button className={styles.card} onClick={copy}>
                <h2>Click to copy share link</h2>
                <p className='text-sm'>{shareLink}</p>
              </button>
             }
          </div>

        </div>

        {/* <div className={styles.grid}>
          {lists.length > 0 && lists.map((list, index) => (
            <List list={list} key={index} className={styles.card}/>
          ))}
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>
        </div> */}
      </main>
    </>
  )
}
